name: publish version
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SUMMERWEB_NPM_PUBLISH_TOKEN }}
          NPM_TOKEN: ${{ secrets.SUMMERWEB_NPM_PUBLISH_TOKEN }}
